# Generated by Django 6.0.5 on 2026-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='source',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL'), ('APPROVED', 'APPROVED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('REVIEW', 'REVIEW'), ('APPROVED', 'APPROVED')], max_length=50),
        ),
    ]
